### PR TITLE
add waveform plotting

### PR DESCRIPTION
**Pull request by cpankow**

### CODE REVIEW

**Comment by cpankow** [comment]
@scottcoughlin2014 : Let's talk about how to test this. This is a good start though.

**Comment by cpankow** [comment]
@scottcoughlin2014 : This should work with basic functionality, can we test in production?

**Comment by scottcoughlin2014** [comment]
Trying it now

**Comment by scottcoughlin2014** [comment]
@cpankow I could do it locally myself and will accept this. We can discuss next week formatting the plot to show up on results webpage as opposed to just the image itself so that we can render more images with the same form

**Comment by scottcoughlin2014** [comment]
@cpankow running into a production issue because I seem to not be able to find the right `latex` libraries that `matplotlib` wants to make your nicely formatting labels. Anyways it seems fine otherwise will fix when i can

**Comment by cpankow** [comment]
The quick fix is probably to drop the "usetex" rc directive, but the label formatting might need some adjustment if you do. If you have access to the production machine, installing the equivalent of `texlive` or some comprehensive TeX package will probably resolve the issue.

**Pull request merged**
